window.STATIC_DASHBOARD_DATA = {
  generated_at: "2026-09-24T16:48:55.148889Z",
  "real_trades": [],
  "trades": [],
  "monthly_analytics": {
    "REAL1000": {
      "terminal_key": "REAL1000",
      "name": "Vantage REAL (REAL1000)",
      "symbol": "GBPUSD",
      "base_capital": 2000.0,
      "total_deposit_usd": 2000.0,
      "deposits_by_month": {},
      "total_wins": 0,
      "total_losses": 0,
      "total_trades": 0,
      "win_rate": 0.0,
      "total_profit_usd": 0,
      "total_return_pct": 0.0,
      "monthly_series": [],
      "months_available": [],
      "current_month": "2026-09",
      "all_trades_by_month": {}
    },
    "HECTOR": {
      "terminal_key": "HECTOR",
      "name": "Vantage REAL (HECTOR)",
      "symbol": "GBPUSD",
      "base_capital": 200.0,
      "total_deposit_usd": 200.0,
      "deposits_by_month": {},
      "total_wins": 0,
      "total_losses": 0,
      "total_trades": 0,
      "win_rate": 0.0,
      "total_profit_usd": 0,
      "total_return_pct": 0.0,
      "monthly_series": [],
      "months_available": [],
      "current_month": "2026-09",
      "all_trades_by_month": {}
    },
    "VANTAGE": {
      "terminal_key": "VANTAGE",
      "name": "BOT-1000 (MARO Demo)",
      "symbol": "GBPUSD",
      "base_capital": 1000.0,
      "total_deposit_usd": 1000.0,
      "deposits_by_month": {},
      "total_wins": 0,
      "total_losses": 0,
      "total_trades": 0,
      "win_rate": 0.0,
      "total_profit_usd": 0,
      "total_return_pct": 0.0,
      "monthly_series": [],
      "months_available": [],
      "current_month": "2026-09",
      "all_trades_by_month": {}
    },
    "PEPPERSTONE": {
      "terminal_key": "PEPPERSTONE",
      "name": "smart+IA (Oro Demo)",
      "symbol": "XAUUSD",
      "base_capital": 2000.0,
      "total_deposit_usd": 2000.0,
      "deposits_by_month": {},
      "total_wins": 0,
      "total_losses": 0,
      "total_trades": 0,
      "win_rate": 0.0,
      "total_profit_usd": 0,
      "total_return_pct": 0.0,
      "monthly_series": [],
      "months_available": [],
      "current_month": "2026-09",
      "all_trades_by_month": {}
    }
  },
  "last_sync": "2026-09-24 09:48:55"
};
